translate_emoticons_to_Vietnamese = {
    "colonbigsmile": "cười ngoác mồm",
    "colonsmilesmile": "vui mừng",
    "colonsmallsmile": "nghịch ngợm",
    "colonsmile": "cười",
    "colonsadcolon": "khóc",
    "colonsad": "buồn",
    "colonsurprise": "ngạc nhiên",
    "colonlovelove": "đỏ bừng",
    "colonlove": "yêu",
    "coloncontemn": "dễ thương",
    "coloncc": "",  # Icon :_
    "coloncolon": "rất hạnh phúc",
    "colonhihi": "cười hạnh phúc",
    "doubledot": "bối rối",
    "colondoublesurprise":"Tức giận",
    "vdotv":"vân vân",
    "dotdotdot":"vân vân",
    "fraction":"/",
    "cplusplus":"c++",
    "csharp":"c#",
}

pro_noun = [
    "wzjwz84", "wzjwz144", "wzjwz288", "wzjwz306", "wzjwz298", "wzjwz82", "wzjwz125",
    "wzjwz10", "wzjwz155", "wzjwz184", "wzjwz56", "wzjwz57", "wzjwz58", "wzjwz228",
    "wzjwz260", "wzjwz170", "wzjwz42", "wzjwz20", "wzjwz266", "wzjwz96", "wzjwz234",
    "wzjwz148", "wzjwz322", "wzjwz223", "wzjwz240", "wzjwz320", "wzjwz160", "wzjwz287",
    "wzjwz19", "wzjwz50", "wzjwz172", "wzjwz192", "wzjwz13", "wzjwz210", "wzjwz290", 
    "wzjwz31", "wzjwz254", "wzjwz215",  "wzjwz275", "wzjwz147", "wzjwz33", "wzjwz143",
    "wzjwz185", "wzjwz136", "wzjwz110", "wzjwz32", "wzjwz9", "wzjwz113", "wzjwz167",
    "wzjwz186", "wzjwz76", "wzjwz179", "wzjwz95", "wzjwz141", "wzjwz165", "wzjwz126",
    "wzjwz34", "wzjwz151", "wzjwz49", "wzjwz64", "wzjwz145", "wzjwz77", "wzjwz38",
    "wzjwz90", "wzjwz91", "wzjwz118", "wzjwz206", "wzjwz268", "wzjwz248", "wzjwz207",
    "wzjwz216", "wzjwz296", "wzjwz309", "wzjwz200", "wzjwz44", "wzjwz217", "wzjwz308",
    "wzjwz100", "wzjwz7", "wzjwz142", "wzjwz40", "wzjwz41", "wzjwz258", "wzjwz271",
    "wzjwz109", "wzjwz150", "wzjwz261", "wzjwz280", "wzjwz183", "wzjwz39", "wzjwz188",
    "wzjwz65", "wzjwz267", "wzjwz189", "wzjwz161", "wzjwz208", "wzjwz209", "wzjwz163",
    "wzjwz178", "wzjwz259","wzjwz324", "wzjwz174", "wzjwz252", "wzjwz159", "wzjwz311",
    "wzjwz157", "wzjwz239", "wzjwz127", "wzjwz177", "wzjwz237", "wzjwz129", "wzjwz130",
    "wzjwz83", "wzjwz253", "wzjwz199", "wzjwz325", "wzjwz146", "wzjwz292", "wzjwz256",
    "wzjwz212", "wzjwz281", "wzjwz300", "wzjwz73", "wzjwz323", "wzjwz123", "wzjwz243",
    "wzjwz169", "wzjwz62", "wzjwz98", "wzjwz99", "wzjwz53", "wzjwz187", "wzjwz11",
    "wzjwz104", "wzjwz278", "wzjwz262", "wzjwz81", "wzjwz6", "wzjwz86", "wzjwz48",
    "wzjwz301", "wzjwz270", "wzjwz107", "wzjwz257", "wzjwz74", "wzjwz3", "wzjwz119",
    "wzjwz196", "wzjwz303", "wzjwz85", "wzjwz235", "wzjwz236", "wzjwz153", "wzjwz103",
    "wzjwz18", "wzjwz263", "wzjwz139", "wzjwz21", "wzjwz276", "wzjwz291", "wzjwz315",
    "wzjwz316", "wzjwz92", "wzjwz226", "wzjwz25", "wzjwz245", "wzjwz327", "wzjwz310",
    "wzjwz289", "wzjwz251", "wzjwz97", "wzjwz180", "wzjwz181", "wzjwz222", "wzjwz35", 
    "wzjwz312", "wzjwz202", "wzjwz203", "wzjwz12", "wzjwz75", "wzjwz205", "wzjwz158",
    "wzjwz80", "wzjwz82", "wzjwz70", "wzjwz71", "wzjwz72", "wzjwz274","wzjwz101", 
    "wzjwz1", "wzjwz182", "wzjwz137", "wzjwz269", "wzjwz27", "wzjwz121", "wzjwz122", 
    "wzjwz277", "wzjwz321", "wzjwz307", "wzjwz30", "wzjwz198", "wzjwz211", "wzjwz286",
    "wzjwz22", "wzjwz246", "wzjwz302", "wzjwz213", "wzjwz297", "wzjwz133", "wzjwz194",
    "wzjwz233", "wzjwz14", "wzjwz134", "wzjwz168", "wzjwz87", "wzjwz88", "wzjwz89",
    "wzjwz255", "wzjwz214", "wzjwz204", "wzjwz111", "wzjwz54", "wzjwz229", "wzjwz230",
    "wzjwz282", "wzjwz283", "wzjwz284", "wzjwz285", "wzjwz171", "wzjwz156", "wzjwz227",
    "wzjwz23", "wzjwz238", "wzjwz120", "wzjwz93", "wzjwz304", "wzjwz299", "wzjwz28",
    "wzjwz15", "wzjwz293", "wzjwz140", "wzjwz191", "wzjwz116", "wzjwz106", "wzjwz46", 
    "wzjwz201", "wzjwz16", "wzjwz17", "wzjwz8", "wzjwz138", "wzjwz250", "wzjwz132",
    "wzjwz173", "wzjwz59", "wzjwz197", "wzjwz4", "wzjwz5", "wzjwz317", "wzjwz36",
    "wzjwz37", "wzjwz68", "wzjwz69", "wzjwz117", "wzjwz154", "wzjwz221", "wzjwz218",
    "wzjwz67", "wzjwz319", "wzjwz108", "wzjwz78", "wzjwz61", "wzjwz176", "wzjwz225",
    "wzjwz249", "wzjwz164", "wzjwz105", "wzjwz294", "wzjwz241", "wzjwz102", "wzjwz47", 
    "wzjwz265", "wzjwz264", "wzjwz24", "wzjwz79", "wzjwz112", "wzjwz29", "wzjwz193",
    "wzjwz295", "wzjwz220", "wzjwz26", "wzjwz232", "wzjwz219", "wzjwz273", "wzjwz326", 
    "wzjwz279", "wzjwz128", "wzjwz166", "wzjwz272", "wzjwz162", "wzjwz131", "wzjwz60",
    "wzjwz224", "wzjwz231", "wzjwz242", "wzjwz43", "wwzjwz305", "wzjwz94", "wzjwz55",
    "wzjwz114", "wzjwz66", "wzjwz149", "wzjwz152", "wzjwz247", "wzjwz313", "wzjwz314",
    "wzjwz45", "wzjwz115",  "wzjwz318", "wzjwz63",  "wzjwz124", "wzjwz2", "wzjwz175",
    "wzjwz244", "wzjwz244", "wzjwz51", "wzjwz52", "wzjwz135", "wzjwz190",   
]

#Stop word
stop_words = [
    'a', 'ai', 'anh', 'ba', 'biết', 'buổi', 'bán', 'bên', 'bước', 'bạn', 'bản', 'bấy', 'bằng', 'bị', 'bỏ', 'bộ',
    'bởi', 'bức', 'cao', 'cha', 'chiếc', 'cho', 'chung', 'chuyển', 'chính', 'chú', 'chúng', 'chăng', 'chơi', 'chưa',
    'chắc', 'chỉ', 'chị', 'chịu', 'chọn', 'chớ', 'chợt', 'chứ', 'con', 'cuối', 'cuốn', 'cuộc', 'càng', 'các', 'cái',
    'cây', 'còn', 'có', 'cô', 'cùng', 'căn', 'cơ', 'cơn', 'cả', 'cấp', 'cần', 'cậu', 'của', 'cứ', 'do', 'duy', 'dài',
    'dành', 'dào', 'dù', 'dùng', 'dưới', 'dạ', 'dẫn', 'dễ', 'dữ', 'em', 'giảm', 'giống', 'giờ', 'giữ', 'giữa', 'gây',
    'gì', 'gần', 'gồm', 'hay', 'hiểu', 'hoặc', 'hãy', 'hơn', 'hết', 'họ', 'hỏi', 'khi', 'khiến', 'khoảng', 'khá', 'khác',
    'khó', 'không', 'khỏi', 'kể', 'loại', 'luôn', 'là', 'làm', 'lâu', 'lên', 'lòng', 'lúc', 'lại', 'lấy', 'lần', 'lớn', 'lời',
    'mang', 'muốn', 'mà', 'mình', 'mạnh', 'mất', 'mọi', 'mối', 'mỗi', 'mới', 'mở', 'mức', 'nay', 'ngay', 'nghe', 'nghĩ', 'ngoài',
    'nguồn', 'ngày', 'người', 'ngọn', 'ngọt', 'ngồi', 'nhanh', 'nhau', 'nhiều', 'nhé', 'nhìn', 'nhóm', 'như', 'nhưng', 'nhất', 'nhận',
    'nhỏ', 'nhớ', 'nhờ', 'những', 'nào', 'này', 'nên', 'nó', 'nói', 'năm', 'nơi', 'nước', 'nếu', 'nền', 'nọ', 'nữa', 'phía', 'phải',
    'phần', 'phỏng', 'qua', 'quay', 'quá', 'quả', 'quận', 'ra', 'rõ', 'rất', 'rằng', 'rồi', 'sang', 'sao', 'sau', 'so', 'suýt', 'sắp',
    'sẽ', 'số', 'sớm', 'sự', 'tay', 'thanh', 'theo', 'thiếu', 'thoạt', 'thuộc', 'thà', 'tháng', 'thêm', 'thì', 'thích', 'thôi', 'thường',
    'thấp', 'thấy', 'thậm', 'thật', 'thế', 'thứ', 'tin', 'trong', 'tránh', 'trên', 'trước', 'trả', 'tuy', 'tuổi', 'tên', 'tìm', 'tính', 'tôi',
    'tăng', 'tại', 'tạo', 'tấm', 'tấn', 'tốt', 'tớ', 'tới', 'từ', 'từng', 'tự', 'việc', 'và', 'vài', 'vào', 'vèo', 'vì', 'vùng', 'vượt', 'vẫn',
    'vậy', 'về', 'với', 'vở', 'vừa', 'xa', 'xem', 'xin', 'xuống', 'à', 'ào', 'ái', 'ít', 'ý', 'ăn', 'đang', 'điều', 'điểm', 'đáng', 'đâu', 'đây',
    'đã', 'đó', 'đúng', 'đưa', 'được', 'đạt', 'đầy', 'đặt', 'đến', 'đều', 'để', 'đủ', 'ơ', 'ư', 'ạ', 'ấy', 'ắt', 'ờ', 'ở', 'ừ', '.'
            ]

spell_correct_word = {
    "phong":"phòng",
    "đươc":"được",
    "việt":"việc",
    "rât":"rất",
    "tân":"tận",
    "dể":"dễ",
    "sơ":"sở",
    "failse":"sai",
    "tiếng":"tiến",
    "hiều":"hiểu",
    "quoa":"qua",
    "tự":"từ", #
    "hưng":"hứng",
    "cóc":"có",
    "bào":"bài",
    "thắng":"thẳng", #
    "kháo":"khảo", #
    "tinh":"tình", 
    "giao":"giáo", #
    "chường":"chương",
    "giểu":"hiểu",
    "truyển":"truyền",
    "dộ":"độ",
    "va":"và",
    "hoà":"hòa",
    "dậy":"dạy",
    "chật":"chất",
    "khiền":"khiến",
    "giang":"giảng",
    "đông":"động",
    "nang":"năng",
    "đạ":"đạt",
    "thê":"thể",
    "tảibỏ":"tải bỏ", #
    "sính":"sinh",
    "&":"và",
    "tìa":"tài",
    "sinn":"sinh",
    "av":"anh văn ",
    "chật":"chất",
    "work group":"làm việc nhóm",
    "thê":"thể",
    "silde":"slide",
    "max":"rất",
    "giàng":"giảng",
    "tính":"tình", #
    "môt":"một",
    "gíao":"giáo",
    "bỗ":"bổ",
    "kinh":"kính",
    "đở":"đỡ",
    "ràng":"dàng",
    "thết":"thiết",
    "áp":"án",
    "hổ":"hỗ",
    "hơp":"hợp", 
    "ta":"tra",
    "dề":"dễ",
    "dijktra":"dijkstra", #
    "tiếc":"tiết",
    "nhiểu":"nhiều",
    "thướng":"hướng",
    "thuc":"thực",
    "nhũng":"những",
    "ngiêm":"nghiêm",
    "tính":"tình", #
    "giản":"giãn",
    "sự":"sử",
    "lở":"lỡ",
    "ngọn":"gọn",
    "loàng":"loằng",
    "lài":"bài",
    "dẽ":"dễ",
    "chon":"chọn",
    "them":"thêm",
    "dẩn":"dẫn",
    "hướng":"hứng",
    "nhiết":"nhiệt",
    "nghung":"những",
    "vu":"vụ",
    "nhìu":"nhiều",
    "nối":"nội",
    "phụ":"phục",
    "tẳng":"tảng",
    "hồ":"hỗ",
    "co":"cho",
    "bao":"bảo",
    "thự":"thực",
    "quí":"quý",
    "niền":"niềm",
    "giành":"dành",
    "nghành":"ngành",
    "cộng":"công",
    "vần":"vấn", #
    "thuân":"thuận",
    "chổ":"chỗ",
    "chích":"chính",
    "thình":"tình",
    "sự":"sử",
    "hơp":"hợp",
    "xuất":"suất",
    "giản":"giảng",
    "suôn":"suông",
    "thế":"thể",
    "dạt":"dạy",
    "bải":"bài",
    "dến":"đến",
    "phầm":"phần",
    "thương":"thường",
    "hỗi":"hỗ",
    "thắm":"thấm",
    "sương":"xương",
    "cận":"cặn",
    "day":"dạy",
    "pro":"đỉnh",
    "lẫn":"lảng",
    "vê":"về",
    "deadline":"", #
    "hiễu":"hiểu",
    "kỹ":"kĩ",
    "bụt":"bục",
    "cương":"cường",
    "thưc":"thực", 
    "viện":"viên",
    "khắn":"khăn",
    "khoá":"khóa",
    "sat":"sát",
    "khản":"khàn",
    "hiêu":"hiểu",
    "gủi":"gũi",
    "cọc":"cộc",
    "dược":"được",
    "giời":"giờ",
    "đê":"đề",
    "dạng":"dạn",
    "giạy":"dạy",
    "nhiêt":"nhiệt",
    "nhiêu":"nhiều",
    "đật":"đạt",
    "của":"cửa",
    "dạ":"dạy",
    "thưởng":"thường",
    "tư":"tự",
    "pháp":"pháp",
    "dạnh":"dạy",
    "tmf" : "tìm",
    "tưởng":"tương",
    "đọng":"động",
    "chi":"cho",
    "kiễn":"kiến",
    "lỳ":"lì",
    "đặt":"đạt",
    "lập":"lặp",
    "gán":"gắn",
    "lước":"lướt",
    "dúng":"đúng",
    "bồ":"bổ",
    "vầ":"và",
    "hụt":"hết",
    "giãng":"giảng",
    "vên":"viên",
    "khôg":"không",
    "vừ":"từ",
    "nhiếu":"nhiều",
    "thúc":"thức",
    "dạt":"đạt",
    "thiên":"thiện",
    "đắng":"đắn",
    "kiếm":"kiến",
    "trể":"trễ",
    "lắp":"lặp",
    "đên":"đến",
    "nà":"và",
    "gọc":"gọn",
    "thoả":"thỏa",
    "dụng":"dung",
    "trọ":"trợ",
    "hòng":"lòng",
    "kiền":"kiến",
    "liều":"liệu",
    "thậy":"thầy",
    "dầy":"đầy",
    "hoat":"hoạt",
    "sô":"số",
    "đới":"đối",
    "nhât":"nhật",
    "thâm":"quá", #
    "sẻ":"sẽ",
    "thông":"thống",
    "dọng":"giọng",
    "tiềm":"tìm",
    "têu":"yêu",
    "cung":"cùng",
    "xác":"sát",
    "đệ":"đề",
    "tậm":"tâm",
    "hiệu":"hiểu",
    "bàu":"bài",
    "giảnh":"dành",
    "traning":"đào tạo",
    "vủi":"vui",
    "thứ":"thức",
    "tâp":"tập",
    "đò":"đồ",
    "truyên":"truyền",
    "kiệp":"kịp",
    "sữa":"sửa",
    "chấy":"chất",
    "triền":"triển",
    "rôi":"rồi",
    "cu":"cụ",
    "thơi":"thời",
    "kiên":"kiến",
    "hiên":"hiện",
    "thác":"thắc",
    "cám":"cảm",
    "cở":"cơ",
    "dung":"dụng",
    "mớ":"mở",
    "xim":"xin",
    "hổi":"hỏi",
    "cũng":"cung",
    "lượt":"lược",
    "trăc":"trắc",
    "lâp":"lập",
    "nhác":"nhắc",
    "viến":"viên",
    "chính":"chỉnh",
    "vơi":"với",
    "bi":"bị",
    "hôi":"hội",
    "huyến":"huyết",
    "thẻ":"thể",
    "tam":"tham",
    "hình":"tình", 
    "mốt":"một",
    "rắt":"rất",
    "chê":"chế",
    "khắc":"khắt",
    "lát":"loát",
    "vậy":"vật",
    "dế":"dễ",
    "rỏ":"rõ",
    "biện":"biên", #
    "buối":"buổi",
    "bai":"bài",
    "hoạ":"họa",
    "soản":"soạn",
    "liêu":"liệu",
    "năng":"nâng",
    "nhannh":"nhanh",
    "đội":"đôi",
    "rễ":"dễ",
    "hắt":"hất",
    "kho":"khó",
    "thây":"thầy",
    "kiển":"kiểm",
    "vi":"ví",
    "lương":"lượng",
    "đế":"đến",
    "vã":"và",
    "cuỗi":"cuối",
    "đễ":"dễ",
    "thày":"thầy",
    "dân":"dẫn",
    "đây":"đầy",
    "sưc":"sức",
    "điểu":"điều",
    "mô":"môn",
    "gẫn":"gần",
    "đều":"điều",
    "buốn":"buồn",
    "mải":"mái",
    "tôt":"tốt",
    "song":"sống",
    "cung":"củng",
    "hạnh":"hành",
    "vói":"với",
    "lần":"lẫn", #
    "gạy":"dạy",
    "tiêp":"tiếp",
    "bào":"bài",
    "hung":"hứng",
    "trao":"trau",
    "đạng":"dạng",
    "vỉên":"viên",
    "danh":"dành",
    "cuả":"của",
    "xắp":"sắp",
    "nang":"nâng",
    "trong":"trọng",
    "đẩy":"đầy",
    "câu":"cầu",
}




 
